name: 'Submit LAVA job'
description: 'Submit LAVA test job'
inputs:
  job_definition:
    description: 'Test job definition to submit'
    required: true
  lava_token:
    description: 'Authentication token for job submission'
    required: true
  lava_url:
    description: 'URL of LAVA instance'
    required: true
  wait_for_job:
    description: 'Wait for job completion and stream logs'
    default: false
  fail_action_on_failure:
    description: 'Marks action failed in any test result is "fail". Requires wait_for_job set to "true"'
    default: true
  fail_action_on_incomplete:
    description: 'Marks action failed in case test jobs ends as Incomplete or is Canceled'
    default: true
  save_result_as_artifact:
    description: 'Save test results as JUNIT XML file'
    default: false
  save_job_details:
    description: 'Save job details as JSON file'
    default: false
  result_file_name:
    description: 'File name in which the test results will be stored. Defaults to test-results-<jobID>.
      If the file with the same name is already stored as workflow artifact it will be overwritten.
      This option is useful for keeping clean results in case of re-running test jobs.'

runs:
  using: 'node20'
  main: 'submit.js'
